-- Insert sample students for Public Health program at Makeni Campus

-- Insert all students
INSERT INTO students (appid, name, program, campus, faculty, department, report_status) VALUES
('19565', 'KALIE LANSANA MARAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19601', 'UNISA  LUGBU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19602', 'Mariatu  Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19610', 'ANTONETTE JENEBA SAMURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19613', 'ABUBAKARR KABBA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19615', 'HASSAN KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19625', 'SATTU LOOBA VANDI', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19636', 'Amadu Kanda', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19675', 'ALHAJI SIDIKIE KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19699', 'Nancy Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19768', 'HAWANATU BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19798', 'FATMATA TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19860', 'SESAY  ZAINAB', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19861', 'JOHN BAI THORONKA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19894', 'ABDUL CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19924', 'Rugiatu kadiatu  Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19957', 'WURIE SILLAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19959', 'CECILIA KUMBA MANI', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('19997', 'Adama Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20003', 'KAMARA  MOMOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20026', 'Mabinty Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20042', 'ABDUL KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20066', 'FATMATA CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20128', 'Fatmata F. Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20129', 'Alieu Katara Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20153', 'JABBIE FATMATA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20160', 'ALPHA TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20164', 'BANGURA AMINATA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20168', 'ALEX SAS  SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20184', 'MOHAMED  WONGO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20198', 'FATMATA I SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20243', 'Fatmata Binta Idriss Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20251', 'Abu Bakarr Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20265', 'FODAY A KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20334', 'MARIATU BAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20342', 'Alimatu  Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20346', 'Alhaji Musa Madina Bah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20370', 'SYLVANUS L BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20386', 'Michael Bockarie  Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20398', 'HENRY SEIKO KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20488', 'Janet Finda Ngaujah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20536', 'Fatmata  Sidiyankay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20554', 'HELLEN MATILDA CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20583', 'IBRAHIM  SHEKA  SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20648', 'Memunatu  Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20661', 'HAJA  KUYATEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20664', 'JESSE MARK PAPAYO SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20679', 'Robert Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20709', 'Regina Hannah Kabba', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20739', 'SYLVIA HUMU TARAWALLIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20756', 'ANDREW FODAY   SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20768', 'ZAINAB  SAFFA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20810', 'RASHIED JUNIOR SIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20815', 'Abibatu Aishatu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20826', 'MOHAMED BALIE BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20835', 'EMELIA AYO KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20865', 'SALAMATU MOHAMED  JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20902', 'MARIATU SAMO BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20924', 'Isatu  Kabba', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('20973', 'AMADU SORIE KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21005', 'SULAIMAN DAUDA  KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21007', 'Marion Sanphanatu Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21032', 'Hawanatu Marie Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21071', 'Musu Manteneh Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21088', 'ISATA  KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21139', 'ALPHAJOR  MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21212', 'Mahawa Mohamed  Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21215', 'MINKAILU SAHID KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21222', 'SAFFIE LINDA F  JARBOE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21240', 'ELIZABETH F.  BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21248', 'ZACKARIA BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21254', 'Kadiatu Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21282', 'M' BALU KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21300', 'REJOICE KUMBA BRIMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21376', 'RAMATU   CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21442', 'MAMUSU FORNAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21450', 'Elizabeth Aminata Conteh Lelleh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21469', 'AMADU  CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21481', 'ALHASSAN TARAWALIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21498', 'RAMATU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21517', 'Fatima I Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21521', 'Haja Salamatu Kanu', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21572', 'Alieu Bah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21580', 'MASERAY BUNDU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21608', 'Mohamed Ibrahim   Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21622', 'BRIMA KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21638', 'MOHAMED ALIE TARAWALIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21645', 'Mamusu Beatrice Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21649', 'JOSEPHINE JATU SANKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21651', 'AMINATA H. CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21669', 'KHADIJATU  SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21683', 'EMMANUEL  KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21729', 'ABDULAI FODAY THOLLEY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21737', 'OSMAN  THOLLEY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21756', 'AGNES PETERNATU KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21775', 'Fanta  Haja Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21822', 'HASSAN   SAYGBA KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21832', 'SAWUDATU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21863', 'Gloria IYE  Samura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21867', 'ZAINAB HANNAH KEBE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21882', 'Alusine Mohamed  Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21912', 'MOHAMED BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21924', 'Hassan  Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21929', 'Tenneh Titi Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21965', 'HAWANATU S. KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('21984', 'Tejan Mohamed Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22018', 'FATMATA S.M KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22047', 'PETER  TUCKER', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22058', 'MOHAMED KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22067', 'IBRAHIM MD  KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22070', 'MOSES TAYIO  SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22082', 'Haja  Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22095', 'MOHAMED KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22107', 'SAFFA  MORIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22108', 'JOHNNY  ELIJAH  KALLON', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22156', 'AMINATA  K TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22169', 'Yusif Kesso  Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22185', 'ABIBATU BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22198', 'Aminata sheriffatu  Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22212', 'Fanta Haja Fofanah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22220', 'ABDUL NELSON COLE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22271', 'NANAH  KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22320', 'DANIEL  KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22329', 'DAVID ALIMAMY  SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22375', 'Minkailu Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22378', 'YUSIF SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22384', 'MARIE  KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22388', 'ABDULAI MOI CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22389', 'Issa Shaka  Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22415', 'ALHASSAN KELPHALA MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22435', 'MARIAN  KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22449', 'KADIATU HASSAN KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22467', 'JOHN T. KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22531', 'BALLA MARAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22540', 'Massah Kargbo', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22582', 'Adamsay Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22601', 'ALIE P.  CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22609', 'HAWANATU KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22626', 'Alma Sheriff', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22661', 'Tapsiru Ayo Carew', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22663', 'Aminata Ramadan Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22681', 'Mohamed Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22697', 'Santigie Turay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22703', 'CHRISTIAN  TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22709', 'SALIMATU JONTA KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22715', 'Fatmata  I  Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22749', 'SULAIMAN  TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22812', 'Milton Douglas Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22820', 'HAJA S. CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22823', 'Fatmata Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22836', 'HAJA S. BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22892', 'PRINCE SELLU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22918', 'ALUSINE  F BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22987', 'ALUSINE NOAH KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('22996', 'MOHAMED KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23034', 'MABINTY  KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23094', 'Alimamy Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23108', 'FATMATA BINTA JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23114', 'ESTHER JANE PATTY KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23116', 'MORLAI B. KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23122', 'EDMOND ABU  KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23152', 'AMINATA SUMAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23187', 'AMINATA MARIAMA SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23208', 'Mariama Sia Lebbie', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23211', 'HAWA MARRAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23223', 'ABU BAKARR SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23233', 'KARGBO  MUSA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23250', 'Santigie Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23269', 'Samura Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23273', 'AMINATA B KABBA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23285', 'MARIAMA TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23291', 'FINDA  LAMIN', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23314', 'EMMANUEL  GANDA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23325', 'YAYAH KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23347', 'SAFFINATU TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23403', 'Jeneba Binta  Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23439', 'Idrissa  Fofanah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23452', 'Simeon Fofanah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23453', 'MAMUSU T KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23488', 'OSMAN KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23513', 'JOSEPH  NYAKEH STEPHENS', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23534', 'Dabor  Lansana', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23541', 'ABU BAKARR KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23542', 'KUMBA  CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23561', 'FRANCESS VANDI CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23642', 'MUSU BALLA KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23664', 'ABDULRAMAN BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23666', 'MALIGIE KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23689', 'FELIX S. KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23711', 'Makia L Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23729', 'LAMA HASSAN BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23745', 'MABINTY LOVELY  TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23759', 'ALIE MOMOH  KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23760', 'ALIE SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23784', 'Jariatu Fatmata Kabia', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23786', 'Estella  Larkoh Kalokoh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23791', 'AMINATA F. KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23793', 'Mamie Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23800', 'ABDALINE SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23828', 'IBRAHIM SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23854', 'AMINATA  SHAW', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23870', 'HERBERT JOHN DERICK SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23912', 'SALIEU KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23922', 'IDRISSA KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23923', 'Ramatu  Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23924', 'Martha Nurse  Kargbo', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23968', 'MARIAMA MUSTAPHA KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23969', 'SHERIFF  SULLAYMAN  KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23973', 'APRISCILL HUMU JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('23979', 'KADIATU MOHAMED  KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24036', 'Tidankay Angela Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24067', 'Bashiru Benjamin  Mackotie', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24117', 'JOSEPH CASSIM KARGBO', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24118', 'Kadiatu Osman Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24149', 'Memunatu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24242', 'Sorie Ben Dumbuya', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24248', 'David Karifa Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24259', 'Denka Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24262', 'Abdulai James', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24267', 'Sheku Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24285', 'Kellie Ferenkeh Jawara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24299', 'Umu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24321', 'Mbalu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24343', 'Feremusu Sunkarie Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24361', 'MOHAMED KALLAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24366', 'Fatmata Osman Swarray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24389', 'ADAMSAY LAMIN KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24393', 'SAMURA FODAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24414', 'Kadiatu Sankoh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24438', 'ADAMA CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24444', 'DAVID S CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24455', 'Isata Alpha Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24471', 'Kadijatu Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24510', 'Mariatu Christo Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24526', 'Dumbuya Nadmi', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24527', 'Alie Komeh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24531', 'Memunatu Timbo', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24553', 'FATMATA J KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24575', 'JOYCE YAMBASU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24581', 'Dipo Kondawulay Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24593', 'Franklyna Manjia Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24599', 'Fanta Martha Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24605', 'JARIEU SHERIFF BAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24611', 'BRIMA UMARO SAMURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24620', 'Gibrilla A. Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24626', 'Mariatu Sheriff', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24645', 'STELLA WUYATEH SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24651', 'Fatmata G. Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24669', 'ADAMSAY CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24674', 'MANSO JABBIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24675', 'SAIO A CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24676', 'Fatmata Kalokoh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24680', 'Zalan Z Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24693', 'SAHR KAMANOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24703', 'FUDIA ZOROKONG', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24715', 'Juliana Sarah Komeh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24736', 'LAMARANA THORONKA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24763', 'Augustine Sankay Kanu', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24778', 'SONNITA KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24789', 'VERONICA ADAMA KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24794', 'Marie Kanu', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24801', 'Osman Mohamed Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24813', 'MAYEALIE BARNETT SANKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24818', 'Martha Mohamed Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24822', 'CHRISTIANA SENESIE', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24824', 'Mbalu Kargbo', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24855', 'Bob Micheal George Gbamanja', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24857', 'EMMA ABUBAKARR CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24878', 'Zainab Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24888', 'ALPHA UMARO KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24900', 'MEMUNATU BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24910', 'Adama Haja Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24924', 'KADIATU ABDUL MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24950', 'MBALU MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('24953', 'MOHAMED ALIE THULLAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25039', 'Chernor Saw', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25056', 'Mariatu Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25059', 'Mabinty Susan Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25060', 'Aruna Tamba', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25070', 'KADIATU SANTIGIE KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25120', 'Anita Sankoh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25130', 'SANTIGIE Y KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25131', 'ADAMSAY KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25159', 'Mohamed Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25168', 'JOCOB JOSEPH BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25180', 'Fatmata D Shaw', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25191', 'ISATA MARIAMA BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25208', 'ALICE SAMA DUMBUYA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25230', 'OSMAN CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25243', 'Ramatu Mansaray', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25261', 'ALHASSAN CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25286', 'Susan Pieh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25298', 'Faldu Shaw', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25315', 'Henrietta Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25343', 'Jenifa A. Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25350', 'HUMU M. SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25364', 'Kaday Sow', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25383', 'FANTA LAMIN', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25395', 'Zainab Ishmaellatu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25408', 'KHADIJATU SAHIDNATU SANKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25409', 'Fatmata Yarie Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25447', 'EMMANUEL   JUNIOR ALIEU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25454', 'GIBRILLA .I. KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25472', 'John Kuteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25500', 'ABU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25503', 'Isatu J Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25510', 'PRINCE JUNIOR KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25512', 'Salifu Yereh Turay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25516', 'Kadiatu A. Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25531', 'Melisa Sahid', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25561', 'ZAINAB BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25562', 'Fatima Zahra Kargbo', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25564', 'AGNES JACKSON', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25569', 'FATMATA SORINATU TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25578', 'AMINATA NAOMI CONTEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25622', 'WINNIFRED TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25635', 'SALAMATU ALIEU SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25644', 'Kadiatu Fatmata Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25703', 'Keita Sansu', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25720', 'ADAMA M SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25724', 'ALIMAMY YEABU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25729', 'BLESSING POREH JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25733', 'ALEX ALPHA SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25737', 'Kadiatu Daramy', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25755', 'Frances Samuella Rugiatu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25760', 'Hawa Barrie', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25765', 'SORIE JUNIOR KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25766', 'Mabinty Tarawali', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25776', 'Rugiatu Deen Turay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25785', 'REBECCA KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25786', 'Solomon Momoh Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25789', 'GEORGE MOMOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25790', 'MESSEH HAWA TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25798', 'JENEBA BANTAMA SHAW', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25842', 'Elina Mabinty Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25845', 'Alhaji Samirr Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25871', 'JOHN AB MARAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25880', 'ADAMA SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25882', 'Mohamed Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25884', 'Mayealie Christiana Fornah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25886', 'Hawanatu Issa Turay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25892', 'Sallay John Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25924', 'Ramatu Ruth Priscillia Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25952', 'MOHAMED MORSAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25961', 'Bintu Adekola', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25963', 'MUSTAPHA KANU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25964', 'Aminata Bangura', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25985', 'HASSAN THOLLEY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('25998', 'KUMBA MATTIA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26021', 'Marie Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26031', 'Memunatu Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26043', 'Aminata Lamin Marah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26067', 'Kumba Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26152', 'MARIATU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26162', 'POREH SHERIFF', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26223', 'Abdul Ibrahim Fornah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26229', 'ALPHA O THORONKA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26236', 'ISATU KALOKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26258', 'Ansumana Bockarie Kanneh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26277', 'FATMATA BINTA JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26297', 'ABASS ABDUL KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26330', 'MAMUSU MARIATU MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26359', 'BLESSING SASSA MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26368', 'SHEKA M. THOLLEY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26388', 'ISATU KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26440', 'Chernor Turay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26450', 'Marie Kabia', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26460', 'KADIATU KONDEH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26495', 'MASERAY KAMARA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26577', 'MABINTY BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26583', 'MARY KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26626', 'Chernor Abdulai Lee', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26686', 'Sarah Jeneba Conteh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26689', 'Emma Amara Zola Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26693', 'KADIJAH MORRY ALLIEU', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26700', 'SAMUEL ALIE TURAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26739', 'Moses Bockarie Koroma', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26746', 'ZAINAB SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26765', 'DANIEL SHEKA MANSARAY JR', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26841', 'ALIMAMY SESAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26876', 'HAWA BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26886', 'Zainab S. Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26903', 'AMADU SAHR JAMES', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26922', 'MOHAMED MARAH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26923', 'Oluted Amara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26933', 'Fatmata B. Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26955', 'ALHASSAN SANKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26979', 'ARUN KABBA JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26980', 'MAYEANIE MANSARAY', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('26985', 'Usman Ibrahim Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27028', 'Chernor Alieu Jalloh', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27034', 'Saidu Bampia Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27036', 'Amadu Henry Kamara', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27037', 'KADIATU GALLEH JALLOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27068', 'FATMATA D. KOROMA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27100', 'Sorie Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27103', 'AMADU FUAD SANKOH', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27161', 'Eshaka Sesay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27177', 'Isatu Lamarana Bah', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27191', 'Lansana Waggay', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27197', 'PATRICK JOHNSON R. BANGURA', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending'),
('27201', 'Emmanuel Junior Alieu', 'Bachelor of Science with Honours in Public Health', 'Makeni Campus', 'Health Sciences', 'Public Health', 'pending')
ON DUPLICATE KEY UPDATE appid=VALUES(appid);

SELECT 'Sample students inserted successfully!' as message;
